[package]
name = "duck_assistant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figlet-rs = "0.1"
crossterm = "0.27"
ratatui = "0.26"
once_cell = "1.18"

